### PR TITLE
Topic attributes for not existing groups

### LINKED ISSUE #231: Attribute Writing: Create Group if Missing
Similar to `createReference` we need a very simple and stupid API to create an empty group for [constant openPMD records](https://github.com/openPMD/openPMD-standard/blob/1.0.0/STANDARD.md#constant-record-components). Right now, `writeAttribute` calls fail if the group (or data set) do not yet exist (instead of, e.g., creating the group).

@f-schmitt-zih  Is there such an API yet?

Otherwise we need to add it :)

### PR DESCRIPTION
**Pull request by psychocoderHPC**
close #231 Attribute Writing: Create Group if Missing 

extent attribute test case (paralllel/serial) 
  - write attribute to a not existing group
  - validate written attribute
extent `writeAttribute()`  (paralllel/serial) 
  - check if dataset/group exists
  - create group if not exists

### CODE REVIEW

**Comment by psychocoderHPC** [comment]
I checked the performance impact for checking each time if a group/dataset exists.
I compared it to the case where I only handle not existing groups if the opening of a group/dataset fails.

**Result:** Can't see an performance impact.

**Comment by ax3l** [comment]
> I checked the performance impact for checking each time if a group/dataset exists.
I compared it to the case where I only handle not existing groups if the opening of a group/dataset fails.
> 
> Result: Can't see an performance impact.

Did you try with 10-thousands of MPI ranks? ;)
I know it sounds rediculous, but thats the only case where I would expect a visible impact:
10'000 ranks write 1e6 different attributes to non-existing groups.

**Comment by ax3l** [comment]
forgot to write this first: thank you so much for implementing and testing! :sparkles:

File: src/ParallelDataCollector.cpp [hunk 1]
```diff
@@ -475,14 +475,25 @@ namespace splash
...
+
             // attach attribute to the dataset or group
             group.open(handles.get(id), group_path);
             hid_t obj_id = H5Oopen(group.getHandle(), obj_name.c_str(), H5P_DEFAULT);
             if (obj_id < 0)
             {
                 throw DCException(getExceptionString("writeAttribute",
                         "object not found", obj_name.c_str()));
-            }
+                }
```
Comment (ax3l) [inline src/ParallelDataCollector.cpp]: alignment gone wild?

File: src/ParallelDataCollector.cpp [hunk 2]
```diff
@@ -475,14 +475,25 @@ namespace splash
         DCParallelGroup group;
         if (dataName)
         {
+            /** create `obj_name` as a group if not exists
+             *
+             * if the `obj_name` with the given `group_path` not exists than
```
Comment (ax3l) [inline src/ParallelDataCollector.cpp]: oh dang! how do we even know it is a group?
This could be very unexpected behaviour if a user actually just mismatched their `write` and `writeAttribute` call...

Comment (ax3l) [inline src/ParallelDataCollector.cpp]: maybe we should at least enforce `group_path` ends on a `/`?

**Comment by psychocoderHPC** [comment]
This would only show that writing attributes is slow not which case of implementation is slow.
I think writing different attributes in parallel is not allowed, but I need to check if write attribute is a collective operation.


Am 13. September 2016 20:32:34 MESZ, schrieb Axel Huebl <notifications@github.com>:
>> I checked the performance impact for checking each time if a
>group/dataset exists.
>I compared it to the case where I only handle not existing groups if
>the opening of a group/dataset fails.
>> 
>> Result: Can't see an performance impact.
>
>Did you try with 10-thousands of MPI ranks? ;)
>I know it sounds rediculous, but thats the only case where I would
>expect a visible impact:
>10'000 ranks write 1e6 different attributes to non-existing groups.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ComputationalRadiationPhysics/libSplash/pull/250#issuecomment-246778243

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by ax3l** [comment]
it is actually collective afaik.

slow: yes, I did mean "test with both implementations (test & create vs. throw and create)"

File: src/ParallelDataCollector.cpp (hunk 2 above)
Comment (ax3l) [inline src/ParallelDataCollector.cpp]: well, maybe it is fine as long as we also document that behaviour in the public API of write[Global]Attribute

File: src/ParallelDataCollector.cpp [hunk 3]
```diff
@@ -475,14 +475,25 @@ namespace splash
...
+             *   - it is a group because datasets needs to be created before
+             *     attributes were added
+             *   - the group is created
+             */
+            std::string pathAndName(group_path + "/" + obj_name);
+            if(!DCParallelGroup::exists(handles.get(id), pathAndName))
```
Comment (ax3l) [inline src/ParallelDataCollector.cpp]: I don't get what this check does if `/path/to/something/<attribute>` is a data set. still working on existing data sets on appends attributes to?

Comment (ax3l) [inline src/ParallelDataCollector.cpp]: offline result: -> just a weird splash naming. works for both groups and data sets

**Comment by ax3l** [comment]
Please add to [writeGlobalAttribute](https://github.com/ComputationalRadiationPhysics/libSplash/blob/f9ebe2e5752b2b7edc304b1e2297d78112a9fe26/src/include/splash/DataCollector.hpp#L318-L328) and [writeAttribute](https://github.com/ComputationalRadiationPhysics/libSplash/blob/f9ebe2e5752b2b7edc304b1e2297d78112a9fe26/src/include/splash/DataCollector.hpp#L362-L377) of `DataCollector.hpp` and `IParallelDataCollector.hpp`:

```
writeGlobalAttribute:
 /**
  * Writes global attribute to HDF5 file (default group).
  *
+ * If the path to \p name does not exist the missing groups will be created.
  *
  * @param ...

writeAttribute:
  /**
   * Writes an attribute to a single dataset.
   *
   * @param id ID for iteration.
   * @param type Type information for data.
   * @param dataName Name of the dataset in group \p id to write attribute to.
   * If dataName is NULL, the attribute is written for the iteration group.
 + * If the path dataName does not yet exist, missing groups will be created.
   * @param attrName Name of the attribute.
   * @param buf Buffer to be written as attribute.
   */
```

**Comment by psychocoderHPC** [comment]
I checked the code again and `writeGlobalAttribute()` is not using the changed method. Therefore I added no comments for this function call.

**Comment by ax3l** [comment]
thank you! :sparkles: :rocket:
